version: '3.2'
services:
  psql:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=statusbot
      - POSTGRES_DB=statusbot
      - POSTGRES_PASSWORD=devpsql
